### ISSUE TITLE
Board manifests cleanup

### ISSUE THREAD

**Issue by valeros** [Nuclei-Software/platform-nuclei#4]
- Would be great if you could unify indentation in the board manifests.

- If you don't need special fields (for example `mabi`, `march` in `hbird_eval.json` or `board_def`, `variant` in `gd32vf103v_eval.json` manifests), feel free to delete them, as you can safely specify a default value for getting values from a dictionary.

- I'm not aware of the purpose of `download*` sections, but maybe it's a good idea to move it to `upload` section instead of `build`?

**Comment by fanghuaqi** [comment]
Thanks @valeos for your review.
> 
>     * Would be great if you could unify indentation in the board manifests.
**[Huaqi] I will unify indentation soon.**

>     * If you don't need special fields (for example `mabi`, `march` in `hbird_eval.json` or `board_def`, `variant` in `gd32vf103v_eval.json` manifests), feel free to delete them, as you can safely specify a default value for getting values from a dictionary.
**[Huaqi] OK, I can remove it, I leave it empty just in case of some user want to specify this `mabi` amd `march` instead of specify the `core` name, since this `core` name is just for easily using our core without knowing how to specify `mabi` and `march`.**

>     * I'm not aware of the purpose of `download*` sections, but maybe it's a good idea to move it to `upload` section instead of `build`?
**[Huaqi] OK, just review this link https://docs.platformio.org/en/latest/projectconf/section_env_platform.html#more-options, I previously thought only this `build` section in the json file can be overrided in `platformio.ini`, now I see I can overwrite any section in json file, I will move this `download*` to upload sections.**

**Comment by fanghuaqi** [comment]
I considerred about it, this `download` is also part of build, it will affect our compiling options, so I still decide to put it in build section.

**Comment by ivankravets** [comment]
Resolved in https://github.com/Nuclei-Software/platform-nuclei/pull/6
