### ISSUE TITLE
Nuclei SDK build script cleanup

### ISSUE THREAD

**Issue by valeros** [Nuclei-Software/platform-nuclei#5]
Most of the code looks good, a few tips if I may:

- Please don't replace the linker script file by default, do it only if user haven't specified one, for example:

```
if not board.get("build.ldscript", ""):
    env.Replace(LDSCRIPT_PATH=build_ldscript)
```

- In case of a critical error, it might be a good idea to direct error messages to `sys.stderr` instead of just printing them, e.g.

```
sys.stderr.write("build.soc is not defined in board description json file, please check!")
env.Exit(1) 
```

- Probably we can safely remove `makedirs` and `copyfile` imports as they are not used in the code.

- If I'm not mistaken you don't need an additional variable `rtoslibs`, since you can append this RTOS libraries directly to `libs` variable.

- It's minor, but there are some space for eliminating code duplication, for example in `get_extra_soc_board_incdirs` function. Also it might be a good idea to move all functions to the top of the file.

**Comment by fanghuaqi** [comment]
Thanks @valeros  for carefully review of code, I will update it soon. **See my answer in bold.**
> 
> Most of the code looks good, a few tips if I may:
> 
>     * Please don't replace the linker script file by default, do it only if user haven't specified one, for example:
> 
> 
> ```
> if not board.get("build.ldscript", ""):
>     env.Replace(LDSCRIPT_PATH=build_ldscript)
> ```
**[Huaqi] I found that I have allowed to use extra ldscript in https://github.com/Nuclei-Software/platform-nuclei/blob/master/builder/frameworks/nuclei-sdk.py#L107-L114.**
~~~py
if build_ldscript == "":
    ld_script = ""
    if build_download_mode == "":
        ld_script = "gcc_%s.ld" % build_soc
    else:
        ld_script = "gcc_%s_%s.ld" % (build_soc, build_download_mode)

    build_ldscript = join(FRAMEWORK_DIR, "SoC", build_soc, "Board", "${BOARD}", "Source", "GCC", ld_script)
else:
    print("Use user defined ldscript %s" % build_ldscript)
~~~

>     * In case of a critical error, it might be a good idea to direct error messages to `sys.stderr` instead of just printing them, e.g.
> 
> 
> ```
> sys.stderr.write("build.soc is not defined in board description json file, please check!")
> env.Exit(1) 
> ```
**[Huaqi] For this `build.soc`, since we are expecting a valid board config json file, we need user to pass valid `build.soc` value in json file, if they are not do it, we will print error and exit, do you think it is ok to have a default value of `build.soc` and print warning?**
>     * Probably we can safely remove `makedirs` and `copyfile` imports as they are not used in the code.
> 
>     * If I'm not mistaken you don't need an additional variable `rtoslibs`, since you can append this RTOS libraries directly to `libs` variable.
**[Huaqi] I will remove `makedirs` and `copyfile` imports, and for `rtoslibs`, I am using a new variable `rtoslibs` to let user know, the following build library contains in `rtoslibs` are for RTOS library.**, I can add some comment here, and remove `rtoslibs`.

>     * It's minor, but there are some space for eliminating code duplication, for example in `get_extra_soc_board_incdirs` function. Also it might be a good idea to move all functions to the top of the file.

**[Huaqi] Ok, good suggestion, I will modify it soon.**

**Comment by valeros** [comment]
> [Huaqi] I found that I have allowed to use extra ldscript ...

It'd be much more idiomatic if user overrides the linker script in `platformio.ini` file, e.g.:
```
...
board_build.ldscript = path/to/script
...
```

> [Huaqi] For this build.soc, since we are expecting a valid board config json file, we need user to pass valid build.soc value in json file, if they are not do it, we will print error and exit, do you think it is ok to have a default value of build.soc and print warning?

What I meant is that it's a good idea to redirect error messages to a proper standard stream.

**Comment by ivankravets** [comment]
Resolved in https://github.com/Nuclei-Software/platform-nuclei/pull/6
